OENIK_PROG4HF_2020_1_ETZVO0/Library.Web/Controllers/ReaderController.cs
using AutoMapper;
using Library.Data;
using Library.Logic;
using Library.Repository;
using Library.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Web.Controllers
{
    public class ReaderController : Controller
    {

        ILogic logic;
        OlvasoViewModel vm;
        IMapper mapper; 

        public ReaderController()
        {
            LibraryDatabaseEntities1 ctx = new LibraryDatabaseEntities1();
            RepositoryHelper rep = new RepositoryHelper(ctx);
            logic = new LogicClass(rep);
            mapper = MapperFactory.CreateMapper();

            vm = new OlvasoViewModel();
            vm.EditedReader = new Models.Olvaso();
            var readers = logic.GetOlvaso2();
            vm.ListofReaders = mapper.Map<IList<Data.Olvaso>, List<Models.Olvaso>>(readers);

        }

        private Models.Olvaso GetReaderModel(int id)
        {
            Library.Data.Olvaso olvaso = logic.GetOlvaso2(id);
            return mapper.Map<Data.Olvaso, Models.Olvaso>(olvaso);
        }

        // GET: Reader
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("ReaderIndex", vm);
        }

        // GET: Reader/Details/5
        public ActionResult Details(int id)
        {
            return View("ReaderDetails", GetReaderModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (logic.DeleteOlvaso(id)) TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }

        //GET: /Reader/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedReader = GetReaderModel(id);
            return View("ReaderIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Models.Olvaso reader, string editAction)
        {
            if (ModelState.IsValid && reader != null)
            {
                TempData["editResult"] = "Edit OK";
                if(editAction == "AddNew")
                {
                    bool success = logic.InsertOlvaso(reader.Olvasoid, reader.Nev, reader.Cim, reader.Email, reader.Telefonszam, reader.Szuletesidatum);
                }
                else
                {
                    if (!logic.UpdateOlvaso(reader.Olvasoid, reader.Nev, reader.Cim, reader.Email, reader.Telefonszam, reader.Szuletesidatum))
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedReader = reader;
                return View("ReaderIndex", vm);
            }
        }
    }
}

OENIK_PROG4HF_2020_1_ETZVO0/Library.Web/Views/Reader/ReaderDetails.cshtml
@model Library.Web.Models.Olvaso
@{
    ViewBag.Title = "ReaderDetails";
}

<h2>ReaderDetails</h2>

@Html.ActionLink("Back to the list", "Index");

<table>
    <tr>
        <td>ID of the reader</td>
        <td>@Model.Olvasoid</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.Nev)</td>
        <td>@Html.DisplayFor(m => m.Nev)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Cim)</td>
        <td>@Html.DisplayFor(m => m.Cim)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Szuletesidatum)</td>
        <td>@Html.DisplayFor(m => m.Szuletesidatum)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Cim)</td>
        <td>@Html.DisplayFor(m => m.Cim)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Email)</td>
        <td>@Html.DisplayFor(m => m.Email)</td>
    </tr>
</table>

OENIK_PROG4HF_2020_1_ETZVO0/Library.Web/Views/Reader/ReaderEdit.cshtml
@model Library.Web.Models.Olvaso

<h2>Edit one reader</h2>

@using (Html.BeginForm("Edit", "Reader"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Olvasoid)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Olvasoid)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Olvasoid)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Nev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Szuletesidatum)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Szuletesidatum)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Cim)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Cim)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Telefonszam)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Telefonszam)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Email)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Email)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG4HF_2020_1_ETZVO0/Library.Web/Views/Reader/ReaderIndex.cshtml
@model Library.Web.Models.OlvasoViewModel

@{
    ViewBag.Title = "ReaderIndex";
}

<h2>ReaderIndex</h2>

<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("ReaderEdit", Model.EditedReader)

@Html.Partial("ReaderList", Model.ListofReaders)

OENIK_PROG4HF_2020_1_ETZVO0/Library.Web/Views/Reader/ReaderList.cshtml
@model IEnumerable<Library.Web.Models.Olvaso>

<h2>List of readers</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Nev) </th>
            <th>@Html.DisplayNameFor(m => m.First().Szuletesidatum) </th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
    <tr>
        <td>@Html.DisplayFor(m => item.Nev)</td>
        <td>@Html.DisplayFor(m => item.Szuletesidatum)</td>
        <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Olvasoid })</td>
        <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Olvasoid })</td>
        <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Olvasoid })</td>

    </tr>
        }
    </table>
}